name: example
description: Demonstrates how to use the flutter_customizable_calendar package.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_customizable_calendar:
    path: ../
  flutter_bloc: ^8.1.1
  uuid: ^3.0.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
